/**
 * Default Content
 * Consolidated default content used in both initialization and context
 */

export const DEFAULT_CONTENT = {
  heroTitle: "Ready to create",
  heroSubtitle: "something extraordinary?",
  heroDescription: "Transforming luxury retail experiences through innovative product leadership and strategic vision.",
  heroImage: "/luz.jpg",
  heroBadge: "",
  heroStats: [],
  heroCtaText: "",
  heroScrollText: "",
  headerFont: "playfair",
  loadingScreenFirstName: "LUZ",
  loadingScreenLastName: "QUINTANAR",
  loadingScreenTagline: "Product Owner • Luxury Retail",
  aboutTitle: "Turning vision into reality",
  aboutDescription: "Experienced product leader with a passion for luxury retail and fashion technology.",
  aboutMainText: "I am a visionary Product Owner with over a decade of experience transforming luxury retail landscapes through strategic innovation and customer-obsessed design.",
  aboutSecondaryText: "My expertise lies in bridging the gap between ambitious business goals and exceptional user experiences. I've built my career on one fundamental belief: premium products deserve premium experiences.",
  aboutBadge: "",
  aboutTitleSuffix: "",
  aboutApproachTitle: "",
  aboutApproachItems: [],
  aboutImpactTitle: "",
  aboutImpactMetrics: [],
  experienceTitle: "A decade of",
  experienceSubtitle: "transformation",
  experiences: [
    {
      role: "Senior Product Owner",
      company: "Maison Lumière",
      period: "2018 - Present",
      location: "Paris, France",
      achievements: [
        "Spearheaded digital transformation resulting in €25M+ revenue increase",
        "Led cross-functional teams of 15+ across 3 countries",
        "Launched omnichannel platform serving 2M+ customers globally",
        "Achieved 40% increase in online conversion rates",
      ],
      highlight: "Transformed traditional luxury retail into digital-first experiences",
    },
    {
      role: "Product Manager",
      company: "RetailTech Innovations",
      period: "2015 - 2018",
      location: "London, UK",
      achievements: [
        "Managed €15M product portfolio across 8 retail brands",
        "Increased customer engagement by 35% through AI-driven personalization",
        "Reduced time-to-market by 50% with agile methodologies",
        "Built and scaled product team from 5 to 20 members",
      ],
      highlight: "Pioneered data-driven product strategies in luxury retail",
    },
    {
      role: "Junior Product Manager",
      company: "Fashion Forward Startup",
      period: "2012 - 2015",
      location: "Milan, Italy",
      achievements: [
        "Co-launched mobile app with 500K+ downloads in first year",
        "Featured in Vogue Business and WWD for innovation",
        "Grew user base by 300% through strategic partnerships",
        "Established product development processes from ground up",
      ],
      highlight: "Laid foundation for product excellence in emerging fashion tech",
    },
  ],
  experienceBadge: "",
  experienceBottomStats: [],
  skillsTitle: "Mastery through",
  skillsSubtitle: "experience",
  skillsDescription: "A decade of hands-on experience has shaped these core competencies that drive exceptional results in luxury retail product management.",
  certifications: [
    "Certified Scrum Product Owner (CSPO)",
    "Google Analytics Certified",
    "Luxury Brand Management (HEC Paris)",
    "Design Thinking Practitioner",
  ],
  tools: [
    "Jira",
    "Figma",
    "Shopify Plus",
    "Salesforce",
    "Tableau",
    "Miro",
    "Slack",
    "Notion",
  ],
  skillsBadge: "",
  skillsCertificationsTitle: "",
  skillsToolsTitle: "",
  softSkills: [
    { skill: 'Executive Stakeholder Management', icon: '🤝' },
    { skill: 'Cross-Cultural Communication', icon: '🌍' },
    { skill: 'Luxury Customer Psychology', icon: '✨' },
    { skill: 'Change Management', icon: '🔄' },
  ],
  skillsSoftSkillsTitle: "Leadership & Soft Skills",
  projectsTitle: "My Projects",
  projects: [],
  contactTitle: "Ready to create",
  contactSubtitle: "something extraordinary?",
  contactDescription: "Whether you're looking to transform your luxury retail experience or explore new product opportunities, I'd love to hear from you.",
  contactBadge: "",
  contactFormTitle: "",
  contactFormLabels: {
    name: "",
    email: "",
    company: "",
    message: "",
  },
  contactFormPlaceholders: {
    name: "",
    email: "",
    company: "",
    message: "",
  },
  contactSubmitButton: "",
  contactSuccessMessage: "",
  contactErrorMessage: "",
  contactInfoTitle: "",
  contactEmail: "",
  contactLinkedin: "",
  contactPhone: "",
  contactAvailabilityTitle: "",
  contactAvailabilityStatus: "",
  contactAvailabilityDescription: "",
  contactAvailabilityItems: [],
  contactDownloadText: "",
  contactCvPath: "/cv.pdf",
  contactBottomInfo: {
    responseTime: {
      label: "",
      value: "",
    },
    location: {
      label: "",
      value: "",
    },
    languages: {
      label: "",
      value: "",
    },
  },
} as const;
